name: sift

type: ruby

up:
  - ruby
  - bundler

commands:
  build: cargo build
  run-built: bundle exec exe/sift $@
  sift: bundle exec exe/sift $@
  sq: cargo run -- $@
  test: bundle exec rake test && cargo test
  debug: SIFT_LOG_LEVEL=debug bundle exec exe/sift $@

check:
  test: bundle exec rake test
  rust-test: cargo test
