name: sift

type: ruby

up:
  - ruby
  - bundler

commands:
  run-built: bundle exec exe/sift $@
  sift: bundle exec exe/sift $@
  debug: SIFT_LOG_LEVEL=debug bundle exec exe/sift $@
  test: bundle exec rake test

check:
  test: bundle exec rake test
